name: save-logs
description: "Save debug logs"

runs:
  using: composite
  steps:
    - name: Fix log permissions
      run: |
        sudo chown $USER /tmp/lulalib-*.log || echo ""
      shell: bash

    - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: debug-log
        path: /tmp/lulalib-*.logd
