name: Fuzz Testing

permissions:
  contents: read

on:
  schedule:
   - cron: '0 0 * * *' 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Setup golang
      uses: ./.github/actions/golang

    - name: Display Go version
      run: go version
      
    - name: Fuzz Tests
      run: | 
        make test-fuzz