name: Issue Triage Label

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Add triage label
      uses: actions/github-script@91a83c091797b22c5771b1d7178fd0fddacc73ea
      with:
        script: |
          const issueNumber = context.issue.number;
          github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            labels: ['triage']
          });
